### PR TITLE
Update Duo Web SDK to version 2.8

### PR DESCRIPTION
**Pull request by justcolin**

### CODE REVIEW

**Comment by Bigsease30** [comment]
Any change of upgrading this to work with the current version of 1.34? I was able to get it to authenticate but it stays on the special page and never allows access to the wiki site. Also the iframe is not working as expected. Half of the Duo menu is cut off.

**Comment by AaronAtDuo** [comment]
@Bigsease30 We'll take a look and see if we can figure out what it going on.  Please bear with us, as we don't have any Mediawiki experts, so it may take a while.

**Comment by Bigsease30** [comment]
@AaronAtDuo That would be fantastic. Thanks.

**Comment by AaronAtDuo** [comment]
@Bigsease30 In the meantime, can I ask one favor?  We've just fixed the "Issues" tab so it's back on our repos, can you add this as a standalone issue?  That'll make it easier on us to prioritize.

**Comment by Bigsease30** [comment]
@AaronAtDuo No problem. Can you point me to the correct link to create the standalone?

**Pull request merged**
